name: Build and Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  deployments: write


jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository # code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install sphinx myst-parser sphinx-rtd-theme furo

    - name: Build documentation
      run: sphinx-build -b html docs docs/_build/html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        destination_branch: gh-pages
        keep_files: true
        # cname: docs.pymattersim.com
